### ISSUE TITLE
apk is invalid

### ISSUE THREAD

**Issue by ItzDfyz** [jiesou/Android-Screener#13]
idk if the project is alive or not, but still. the problem is that when installing it gives the following: “The application is not installed because its package is invalid (e.g. corrupted)”. maybe it should be installed in some other way but I don't know. phone: realme c30s

**Comment by jiesou** [comment]
download the apk from the [Actions](https://github.com/jiesou/Android-Screener/actions) page first
apk on the Releases page may not be installed due to signature issues
