### ISSUE TITLE
Danger of low resolution

### ISSUE THREAD

**Issue by CharlesLiaoO** [jiesou/Android-Screener#2]
When set the resolution to too low, such as a height lower than 1800 on my phone, it's dangerous because the set buttons are almost covered, and that resolution retains after reboot.

**Comment by jiesou** [comment]
So this app has a feature that will automatically reset the resolution/DPI if left inactive for a period of time after applying it.
But there are still some problems with this feature and it may not work at the moment, please wait for the fix!

**Comment by jiesou** [comment]
If you've broken your phone, you can use the `wm` command from your computer ADB to recover it.

```
adb shell wm size reset
adb shell wm density reset
```
