### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Inconnubro** [jiesou/Android-Screener#7]
Can you make a realese on an apk version please I known it might sound silly

**Comment by krustenkaese23** [comment]
go to actions, click the latest successful build, and click on the download symbol next to the generated artifact, it's a zip file containing the apk.
the download symbol only appears if you are signed in to github

https://github.com/jiesou/Android-Screener/actions/runs/7837981759/artifacts/1232002428
this is the current one

**Comment by Clarobrz** [comment]
Pls upload the apk in other site, i dont found this file to dowload, the link not work

**Comment by Ziyadeyong1** [comment]
the link in the artifact os is already expired

**Comment by jiesou** [comment]
https://github.com/jiesou/Android-Screener/releases/tag/dev
only for test
