### ISSUE TITLE
Wheres link to download

### ISSUE THREAD

**Issue by Denzell0** [jiesou/Android-Screener#8]
I need a link on release to download it please, i don't know where is the apk

**Comment by jiesou** [comment]
https://github.com/jiesou/Android-Screener/releases/tag/dev
only for test

**Comment by Inconnubro** [comment]
Thanks work really well !!

**Comment by vjaykrsna** [comment]
I got error while installing this.
```App not installed as package appears to be invalid ```

**Comment by tamarindojuice** [comment]
> I got error while installing this. `App not installed as package appears to be invalid `

Same here

**Comment by jiesou** [comment]
It may be a problem with the signature of the test package.
Welcome to try again to download a new test package from Github Action.

BTW: If the artifacts in Github Actions is expired and cannot be downloaded, you can fork this project and rebuild it.

**Comment by jiesou** [comment]
Same as #9
