### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by tamarindojuice** [jiesou/Android-Screener#9]
While attempting to install it got the message:

"App not installed as package appears to be invalid "

Honor Magic 5 lite
Android 13 / Magic OS 7.1

**Comment by jiesou** [comment]
It may be a problem with the signature of the test package.
Welcome to try again to download a new test package from Github Action.

BTW: If the artifacts in Github Actions is expired and cannot be downloaded, you can fork this project and rebuild it.
